### ISSUE TITLE
Game crashes when I open a new world

### ISSUE THREAD

**Issue by TAKOMAN1** [Glitchfiend/TerraBlender#23] opened 2022-01-20 06:41 UTC
### What's the issue you encountered?

I opened a new world and the game crashed.

### How can the issue be reproduced?

You can't really, I'm using a mod pack I have created with over 340 mods.

### Logs

https://github.com/AOCAWOL/BYG/files/7902751/latest.log

### Mod Version

1.1.0.70

### Additional information

The mod Not Enough Crashes and the Minecraft launcher itself didn't show me the crash log.

My Fabric loader version is 0.12.12 (which is the latest one for Minecraft 1.18.0)
I checked every mod that could cause the issue, and this mod does.

**Comment by Adubbz** [comment] 2022-01-20 06:43
Duplicate of #22

**Closed as completed by Adubbz** 2022-01-20 06:43 UTC
