### ISSUE TITLE
Weird Biome Placement using Data Packs

### ISSUE THREAD

**Issue by Matthysse** [Glitchfiend/TerraBlender#109] opened 2023-02-05 10:28 UTC
### What's the issue you encountered?

Biomes are placed weirdly and not at their correct context using Terrablender, a modded biome provider and a generation Datpack, in this example I use BOP,  Terrablender and Tectonic.
Here are the results:
![2023-02-05_11 19 59](https://user-images.githubusercontent.com/32510957/216813596-775b846b-2d0e-46a7-b759-a6669f7aa980.png)
Where it should be mountain biomes (like a frozen_peak) it's just a continuation of the plains biome and looks odd.
![2023-02-05_11 21 27](https://user-images.githubusercontent.com/32510957/216813624-9241576c-cf4d-4124-be29-9e7275c53151.png)
On the other side, where it should be a plain biome, it's a totally flat frozen_peak.

### How can the issue be reproduced?

Install Terrablender, Biomes'O'Plenty and Tectonic, do /locate biome minecraft:frozen_peaks and see results

### Logs

https://gist.github.com/Matthysse/c10433d7a6da5fe9f6609917fcba0ed2

### Mod Version

1.1.0.139

### Additional information

On Vanilla minecraft the data pack works perfectly:
![2023-02-05_11 07 26](https://user-images.githubusercontent.com/32510957/216813851-34756e4e-1cc1-4466-8019-cfe170530e22.png)

**Comment by Adubbz** [comment] 2023-02-08 01:46
You seem to have provided the wrong mod version number given that no 1.19.3 version of TerraBlender has that version.

That aside, this would be an issue exclusively with Tectonic. Terralith is also a datapack based world generation mod and (to my knowledge) does not have these issues.

**Comment by Matthysse** [comment] 2023-02-08 07:05
Yeah I tested on both 1.19.2 and 1.19.3, I put a 1 instead of a 2, the latest tested version is in reality 2.1.0.139. It seems indeed that many problems appear when using Tectonic alongside Terrablender (like the underground rivers creating river biomes on the surface). For this latest issue the author of the data pack said that it was due on how Terrablender works.

**Comment by Apollounknowndev** [comment] 2023-04-12 04:13
The issue is caused by Tectonic, there's no way for Terrablender to fix it. I haven't fixed it on Tectonic's end because fixing it would take a massive toll on the performance of the datapack.
Edit: It's been fixed in Tectonic v2.

**Comment by Darkmega18** [comment] 2023-09-03 15:51
~wow, your mods really be doin some weird stuff in the background, apollo.~

**Comment by Adubbz** [comment] 2023-09-04 03:20
Closing this, given it's not something we can resolve on our end

**Closed as completed by Adubbz** 2023-09-04 03:20 UTC
Labels: bug
