### ISSUE TITLE
Terrible world generation performance after ~1000 game days.

### ISSUE THREAD

**Issue by KostromDan** [Glitchfiend/TerraBlender#122] opened 2023-05-26 11:13 UTC
### What's the issue you encountered?

Ryzen 7950x 64gb server generates less than 1 chunk per second. Although in the beginning everything was fine and chunks were generated almost instantly. But over time, the generation rate dropped, dropped and dropped to an unbearable limit. After comprehensive testing, it turned out that either BOP or terrablender causes this problem. If you delete BOP, the generation rate will not change. From which I conclude that terrablender is responsible for the terrible performance. Which is strange, considering that he doesn't have to do anything by himself. After terrablender was removed, performance became excellent and chunks began to be generated almost instantly as at the time of the creation of the world.

### How can the issue be reproduced?

M-Tech-1.3.11 modpack. https://legacy.curseforge.com/minecraft/modpacks/m-tech-1-19-2
If you need world map, i can share it.

### Mod Version

2.0.1.136

### Additional information

Testing:
1)BOP removed
2)BOP and Terrablender removed
https://youtu.be/yzRgHx3po9o

**Comment by KostromDan** [comment] 2023-05-26 20:16
Maybe it caused because worldtype is large biomes

**Comment by Adubbz** [comment] 2023-05-27 22:58
This turned out to be a duplicate of #107

**Closed as completed by Adubbz** 2023-05-27 22:58 UTC
Labels: bug
