### ISSUE TITLE
Game with biomes o plenty crashes and log states terrablender is missing despite the mod being in the mod folder.

### ISSUE THREAD

**Issue by ZeGamingCuber** [Glitchfiend/TerraBlender#77] opened 2022-06-28 17:13 UTC
### What's the issue you encountered?

The game crashes and says terrablender is missing when it's not

### How can the issue be reproduced?

Load a modpack with bop and terrablender

### Logs

[28Jun2022 13:06:32.965] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Flare_The_Folf, --version, 1.19-forge-41.0.45, --gameDir, C:\Users\Berry\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Berry\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, a630c13610c14d40b4685f58ac188ae6, --accessToken, ????????, --clientId, ZjNkNzJiZWItZDA2OC00OWE1LTgzMGItNzQ3OTkzNzJjNDJm, --xuid, 2535439149578536, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.45, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129] [28Jun2022 13:06:32.970] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.1+10.0.1+main.e9521dc3 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0 [28Jun2022 13:06:33.195] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Berry/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT [28Jun2022 13:06:34.330] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Berry\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19-41.0.45\fmlcore-1.19-41.0.45.jar is missing mods.toml file [28Jun2022 13:06:34.333] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Berry\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19-41.0.45\javafmllanguage-1.19-41.0.45.jar is missing mods.toml file [28Jun2022 13:06:34.337] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Berry\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19-41.0.45\lowcodelanguage-1.19-41.0.45.jar is missing mods.toml file [28Jun2022 13:06:34.340] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Berry\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19-41.0.45\mclanguage-1.19-41.0.45.jar is missing mods.toml file [28Jun2022 13:06:34.405] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping! [28Jun2022 13:06:34.531] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: terrablender [28Jun2022 13:06:37.513] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [28Jun2022 13:06:37.522] [main/ERROR] [mixin/]: Mixin config rubidium.mixins.json does not specify "minVersion" property [28Jun2022 13:06:37.557] [main/ERROR] [mixin/]: Mixin config mixin.cleancut.json does not specify "minVersion" property [28Jun2022 13:06:37.603] [main/ERROR] [mixin/]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property [28Jun2022 13:06:37.640] [main/ERROR] [mixin/]: Mixin config radium.mixins.json does not specify "minVersion" property [28Jun2022 13:06:37.676] [main/ERROR] [mixin/]: Mixin config radon.mixins.json does not specify "minVersion" property [28Jun2022 13:06:37.719] [main/ERROR] [mixin/]: Mixin config myrtrees-common.mixins.json does not specify "minVersion" property [28Jun2022 13:06:37.937] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19-forge-41.0.45, --gameDir, C:\Users\Berry\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Berry\AppData\Roaming\.minecraft\assets, --uuid, a630c13610c14d40b4685f58ac188ae6, --username, Flare_The_Folf, --assetIndex, 1.19, --accessToken, ????????, --clientId, ZjNkNzJiZWItZDA2OC00OWE1LTgzMGItNzQ3OTkzNzJjNDJm, --xuid, 2535439149578536, --userType, msa, --versionType, release] [28Jun2022 13:06:38.011] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 29 options available, 0 override(s) found [28Jun2022 13:06:38.140] [main/WARN] [mixin/]: Reference map 'overweightfarming.refmap.json' for overweightfarming.mixins.json could not be read. If this is a development environment you can ignore this message [28Jun2022 13:06:38.174] [main/ERROR] [RadiumConfig/]: Option entity.collisions.fluid for dependency 'entity.collisions.fluid depends on chunk=true' not found. Skipping. [28Jun2022 13:06:38.175] [main/ERROR] [RadiumConfig/]: Option entity.collisions.fluid for dependency 'entity.collisions.fluid depends on chunk.block_counting=true' not found. Skipping. [28Jun2022 13:06:38.177] [main/INFO] [Radium/]: Loaded configuration file for Radium: 93 options available, 0 override(s) found [28Jun2022 13:06:38.268] [main/WARN] [mixin/]: Reference map 'myrtrees-common-refmap.json' for myrtrees-common.mixins.json could not be read. If this is a development environment you can ignore this message [28Jun2022 13:06:38.309] [main/WARN] [mixin/]: Reference map 'naturalist-forge-forge-refmap.json' for naturalist.mixins.json could not be read. If this is a development environment you can ignore this message [28Jun2022 13:06:38.379] [main/WARN] [mixin/]: Reference map 'xtraarrows.mixins.refmap.json' for xtraarrows.mixins.json could not be read. If this is a development environment you can ignore this message [28Jun2022 13:06:38.745] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/level/levelgen/structure/MineShaftPieces$MineShaftPiece (java.lang.ClassNotFoundException: net.minecraft.world.level.levelgen.structure.MineShaftPieces$MineShaftPiece) [28Jun2022 13:06:38.745] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.level.levelgen.structure.MineShaftPieces$MineShaftPiece was not found supplementaries.mixins.json:accessors.MineshaftAccessor [28Jun2022 13:06:39.218] [main/WARN] [mixin/]: Error loading class: link/infra/indium/renderer/render/TerrainRenderContext (java.lang.ClassNotFoundException: link.infra.indium.renderer.render.TerrainRenderContext) [28Jun2022 13:06:39.224] [main/WARN] [mixin/]: Error loading class: ca/spottedleaf/starlight/common/light/StarLightEngine (java.lang.ClassNotFoundException: ca.spottedleaf.starlight.common.light.StarLightEngine) [28Jun2022 13:06:39.266] [main/WARN] [mixin/]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule) [28Jun2022 13:06:39.266] [main/WARN] [mixin/]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin [28Jun2022 13:06:39.728] [main/INFO] [mixin/]: Mixing TextColorMixin from iceberg.mixins.json into net.minecraft.network.chat.TextColor [28Jun2022 13:06:40.253] [main/INFO] [mixin/]: Mixing ScreenMixin from iceberg.mixins.json into net.minecraft.client.gui.screens.Screen [28Jun2022 13:06:40.348] [main/INFO] [mixin/]: Mixing MinecraftMixin from iceberg.mixins.json into net.minecraft.client.Minecraft

### Mod Version

2.0.0.112

**Comment by Adubbz** [comment] 2022-06-28 23:25
Duplicate of #78

**Closed as not planned by Adubbz** 2022-06-28 23:25 UTC
