### ISSUE TITLE
Generating the Nether crashes the singleplayer integrated server

### ISSUE THREAD

**Issue by MScott7** [Glitchfiend/TerraBlender#27] opened 2022-01-24 20:43 UTC
### What's the issue you encountered?

Singleplayer integrated server crashes when entering the nether for the first time in a world. 

Log says `Error executing task on Chunk source main thread executor for minecraft:the_nether` caused by `java.lang.NullPointerException: Cannot invoke "terrablender.worldgen.TBClimate$RTree.search(terrablender.worldgen.TBClimate$TargetPoint, terrablender.worldgen.TBClimate$DistanceMetric)" because "this.trees[uniqueness]" is null`

### How can the issue be reproduced?

1. Create a new world
2. Build and go through a nether portal

Has so far happened every time I've tried to enter the nether in a new world. Tested in two new worlds in survival and creative.

### Logs

https://gist.github.com/MScott7/7bdd610f26253a4ec10a61a5935d9eed

### Mod Version

1.1.0.73

### Additional information

Biomes O' Plenty and Oh The Biomes You'll Go are both present if that matters.

**Comment by xd4rkzghost01** [comment] 2022-01-28 02:07
I have the same trouble here and was thinking it w but with different crash log; with different mod deactivated:

Forge : 39.0.59
(and a load of mods)
OptiFine_1.18.1_HD_U_H4

1st : Without Polymorph ( i was thinking it was the cause)
[crash-2022-01-27_17.23.02-server.txt](https://github.com/Glitchfiend/TerraBlender/files/7955102/crash-2022-01-27_17.23.02-server.txt)

2nd : Now With Polymorph
[crash-2022-01-27_17.34.12-server.txt](https://github.com/Glitchfiend/TerraBlender/files/7955129/crash-2022-01-27_17.34.12-server.txt)

3rd : And finally, i've uninstall everything and re-install all the mod i want to use, but still crash
[crash-2022-01-27_20.38.33-server.txt](https://github.com/Glitchfiend/TerraBlender/files/7955135/crash-2022-01-27_20.38.33-server.txt)

There the "Latest" Log too
[latest.log](https://github.com/Glitchfiend/TerraBlender/files/7955138/latest.log)

Also Same as #22

**Comment by TrueMrOmnipotent** [comment] 2022-01-28 03:37
Same problem as you both hope it is fixed soon.
[crash-2022-01-27_20.34.30-server.txt](https://github.com/Glitchfiend/TerraBlender/files/7955498/crash-2022-01-27_20.34.30-server.txt)

**Comment by ChristianNguyen-Chinag** [comment] 2022-02-02 22:30
Same problem here. I am running the Moonlit Myth problem, but it seems to be a problem with this mod itself
[crash-2022-02-02_23.06.07-server.txt](https://github.com/Glitchfiend/TerraBlender/files/7990471/crash-2022-02-02_23.06.07-server.txt)
.

**Comment by Drea8MHell0** [comment] 2022-02-12 18:54
I am also experiencing this crash error when attempting to enter the Nether in a single-player world. The same Crash Log as MScott77 posted above. It is in a Moonlit Myths Modpack. I have the full crash text file saved if it is needed to submit for investigation. But I don't want to spam the same information as listed above if it isn't necessary. I will attempt to see if I can use a ruined portal, or find a vanilla biome to see if it is just my current choices of biomes for my base that is causing the issue.

**Comment by Adubbz** [comment] 2022-03-08 11:31
Closing this as the code involved in this crash is no longer present on 1.18.2.

**Closed as completed by Adubbz** 2022-03-08 11:31 UTC
