### ISSUE TITLE
1.19.2 Trees fail to generate in most modded biomes after updating from .130 to .136

### ISSUE THREAD

**Issue by LoftyLoftyLoftyLoftyLofty** [Glitchfiend/TerraBlender#106] opened 2022-12-30 16:17 UTC
### What's the issue you encountered?

Multiple biomes fail to generate with trees. 

### How can the issue be reproduced?

Generate modded biomes using .130 instead of .136.
Affected biomes from multiple mods, try with Biomes O' Plenty or Terralith (Ominous woods is a good example)

### Mod Version

1.19.2-2.0.1.136

**Comment by Adubbz** [comment] 2023-01-01 03:46
I can't reproduce this on 1.19.3 or 1.19.2
![image](https://user-images.githubusercontent.com/2765389/210160493-9c0dc8e6-ce26-4c2a-984c-7719918bbe46.png)
![image](https://user-images.githubusercontent.com/2765389/210160528-0e043eec-dd59-4ecc-b0fa-d91e70fe2bd8.png)

**Comment by Aleon4201** [comment] 2023-04-01 04:02
In my case, no trees from Oh the Biomes You'll Go are spawned in the Nether on the new world.
I saw issues of it, I found that there's a problem with Terrablender.

**Comment by Frutiger-AER0** [comment] 2023-04-21 13:49
[https://github.com/AOCAWOL/BYG/issues/1150](url)
The BYQ Issue Tracker has had a few people reporting the same issue. (Me included)

**Comment by RechercheRaptor** [comment] 2023-04-22 05:02
I've been having this same issue and it's really been bugging me, at first I thought it was an OTBYG thing (and made a bug report over on its bug tracker) but it's definitely Terrablender.

The issue is exclusive to modded biome fauna and other features (like crystal clusters) in the Nether and End only. The Overworld biomes seem totally unaffected.

Terrablender beta 1.19.2-2.0.1.130 and Terrablender release 1.19.2-2.0.1.136 don't generate any of the BYG flora (or crystal clusters such as in the Subzero Hypogeal) in the Nether or End.

The earlier versions Terrablender beta 1.19.2-2.0.1.129 and Terrablender release 1.19.2-2.0.1.128 DO properly generate BYG flora. I haven't tested any earlier versions than that so I can't speak for those, but the most recent beta and release have some kind of weird error going on.

**Comment by Frutiger-AER0** [comment] 2023-04-22 07:32
It was every biome for me, at least in the overworld. I never tested the nether or end for me but considering other reports it was likely much the same thing. 

My only explanation I can think of is that if you are using other mods that add biomes or biome changes to these dimensions, Terrablender messes up somewhere and it results in this. 
I've heard reports that changing NBT data in a worlds level file can fix it, but I wasn't properly explained how to do it. (and shouldn't be how the mod works anyway.)

1.18.2 works just fine, it's solely an issue with 1.19

![huh](https://user-images.githubusercontent.com/82814439/233769874-ca5847da-6515-4954-b650-074d99241607.png)

**Comment by RechercheRaptor** [comment] 2023-04-22 08:15
It happened to me even when I had only Oh The Biomes You'll Go and Terrablender in a profile I made specifically to test it, and only in the Nether and End. It's very strange.

**Comment by xyxt1c** [comment] 2023-07-07 14:10
I have the same issue using promenade. Doesnt generate any foliage in the blush sakura grove. Using Terrablender for Nyctophobia. Without Terrablender / Nyctophobia its fine.

MC 1.20.1 TerraBlender-fabric-1.20.1-3.0.0.165.jar

**Comment by DarthShader** [comment] 2023-07-11 23:26
Can confirm this is still an issue on TerraBlender 2.2.0.168 with a fresh install of the following:
Minecraft 1.19.4
Forge 45.1.0
OTBYG 4.0.0.2
CorgiLib 3.0.0.0
GeckoLib 4.2

**Comment by xyxt1c** [comment] 2023-07-12 15:04
> I have the same issue using promenade. Doesnt generate any foliage in the blush sakura grove. Using Terrablender for Nyctophobia. Without Terrablender / Nyctophobia its fine.
> 
> MC 1.20.1 TerraBlender-fabric-1.20.1-3.0.0.165.jar

I have to add: It only happens sometimes. Even with heavily modded terrain and feature generation it's most of the times fine. but sometimes biome features don't generate for modded content. If I generate a new world with the same seed, maybe 1/20 times.

**Comment by mcd256** [comment] 2023-09-06 01:13
Sorry to bring this post back from the dead but I'm still having this problem on 1.19.4. I've spent hours trying to find a fix for it but I'll probably just have to go back to an older version.

**Comment by Adubbz** [comment] 2023-11-19 04:43
This issue should now be addressed in Minecraft 1.19.4 and 1.20.2. Note that the fix will only apply to newly generated worlds when using the latest mod version.

**Closed as completed by Adubbz** 2023-11-19 04:43 UTC
Labels: bug
