### ISSUE TITLE
Crash generating new chunk

### ISSUE THREAD

**Issue by hypernova132** [Glitchfiend/TerraBlender#46] opened 2022-02-27 06:22 UTC
### What's the issue you encountered?

https://pastebin.com/YMYHvZFu
I was exploring my world and it seems the game crashed trying to generate chunk.

### How can the issue be reproduced?

Only possible way I can know how to reproduce this is to use all the mods I have installed and explore any world until a crash happens.

### Logs

https://gist.github.com/hypernova132/cbe136ceab9de3ca23274dbc1d97ae43

### Mod Version

1.1.0.77

**Comment by Orgamorsh** [comment] 2022-03-04 21:29
I'm just going to throw my latest log in here because I am getting the same error.

Log: https://gist.github.com/Orgamorsh/7b417dcaff0e10a3cee472a79bf99369

**Comment by Adubbz** [comment] 2022-03-08 11:47
Closing this as your logs do not suggest this is TerraBlender related. You also have far too many mods to make the issue easily debuggable/reproducible.

**Closed as completed by Adubbz** 2022-03-08 11:47 UTC
